matrix:
  include:
    - language: java
      before_script:
        - mvn -v
      script:
        - mvn clean verify

    - language: go
      before_script:
        - pwd
      script:
        - ls -ltra

notifications:
  slack: effortel-group:P1e0Xos5vRW2rV7Unvyasaqe
