language: java
os:
  - linux
  - osx
sudo: true
before_script: sudo ./before_script_actions.sh
script:
  - mvn clean verify
  - ls -ltra
  - cat kkk.txt

notifications:
  slack: effortel-group:P1e0Xos5vRW2rV7Unvyasaqe
